#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH -p gpu
#SBATCH -J test1
#SBATCH --account=
#SBATCH --gres=gpu:3
#SBATCH -o slurm.out
#SBATCH -e slurm.err
#SBATCH --time=48:00:00

# Rutas persistentes del usuario
export BASE=/nethome/prosei_d/Prosei
CA_ROOT="$BASE/prosei-research-developv2/"
export HOME=$BASE/home
export TMPDIR=$BASE/tmp
export PIP_CACHE_DIR=$BASE/cache/pip
export XDG_CACHE_HOME=$BASE/cache/xdg
export PYTHONUSERBASE=$BASE/cache/python_userbase

# Imagen y VSCode Server (tus rutas actuales)
export SIF_PATH=$BASE/singularity/rag2.sif
export VSCODE_PATH=$BASE/openvscode-server-v1.101.1-linux-x64/bin/openvscode-server

export NODE_HOME=$BASE/node-v22.21.1/node-v22.21.1-linux-x64
export PATH=$NODE_HOME/bin:$PATH

# Pasar Node al contenedor también
export SINGULARITYENV_NODE_HOME=$NODE_HOME
export SINGULARITYENV_PATH="$NODE_HOME/bin:$PATH"

# Proxy (igual que tienes ahora)
export HTTP_PROXY="http://usuario:senha@inet-sys.petrobras.com.br:804"
export HTTPS_PROXY=$HTTP_PROXY
export http_proxy=$HTTP_PROXY
export https_proxy=$HTTP_PROXY
export NO_PROXY="localhost,127.0.0.1,petrobras.com.br,petrobras.biz"
export no_proxy=$NO_PROXY

# CA Certification
export CERT_FILE="$CA_ROOT/petrobras-ca-root.pem"
export REQUESTS_CA_BUNDLE=$CERT_FILE
export SSL_CERT_FILE=$CERT_FILE

# Propagar variables al contenedor
export SINGULARITYENV_HOME=$HOME
export SINGULARITYENV_TMPDIR=$TMPDIR
export SINGULARITYENV_PIP_CACHE_DIR=$PIP_CACHE_DIR
export SINGULARITYENV_XDG_CACHE_HOME=$XDG_CACHE_HOME
export SINGULARITYENV_PYTHONUSERBASE=$PYTHONUSERBASE
export SINGULARITYENV_HTTP_PROXY=$HTTP_PROXY
export SINGULARITYENV_HTTPS_PROXY=$HTTPS_PROXY
export SINGULARITYENV_NO_PROXY=$NO_PROXY
export SINGULARITYENV_http_proxy=$http_proxy
export SINGULARITYENV_https_proxy=$https_proxy
export SINGULARITYENV_no_proxy=$no_proxy 

export SINGULARITYENV_REQUESTS_CA_BUNDLE=$REQUESTS_CA_BUNDLE
export SINGULARITYENV_SSL_CERT_FILE=$SSL_CERT_FILE

# Info útil
export NODEIP=$(ifconfig | grep -oP 'inet\s+\K[\d.]+' | head -n1)
echo $SLURM_JOB_NODELIST
echo "SLURM_JOBID: $SLURM_JOBID"
echo -e "Tunnels:\nssh -L 3001:$NODEIP:3001 -L 3003:$NODEIP:3003 $USER@$NODEIP"

# Lanzar VSCode server dentro del contenedor con GPU
singularity run --nv --fakeroot --writable-tmpfs -B /nethome:/nethome --hostname 0.0.0.0 "$SIF_PATH" \
  bash -c "$VSCODE_PATH --port 3001 --user-data-dir='$HOME' --without-connection-token --host 0.0.0.0 ." &

sleep 48h
